MODULE BITSSMODULE
  USE COMMONS, ONLY : NOPT

  IMPLICIT NONE

  CONTAINS


  SUBROUTINE BITSS(COORDS1, COORDS2)
    USE KEY, ONLY : BITSSMAXITER, BITSSSTEP
    USE BITSS_POTENTIAL, ONLY : DISTANCE, TARGET_DIST
    USE BITSS_LBFGS, ONLY : MINIMISE
    DOUBLE PRECISION, INTENT(INOUT) :: COORDS1(NOPT), COORDS2(NOPT)
    INTEGER :: ITER
    DOUBLE PRECISION :: TARGET_DIST, COORDS(2*NOPT)
    LOGICAL :: MIN_CONVERGED

    TARGET_DIST = DISTANCE(COORDS1, COORDS2)

    DO ITER = 1, BITSSMAXITER
      TARGET_DIST = (1 - BITSSSTEP) * TARGET_DIST

      ! Minimise while updating the constraint coefficients
      MIN_CONVERGED = .FALSE.
      DO WHILE (.NOT. MIN_CONVERGED)
        CALL COMPUTE_COEF(COORDS1, COORDS2)
        COORDS(1:NOPT) = COORDS1
        COORDS(NOPT+1:2*NOPT) = COORDS2
        MIN_CONVERGED = MINIMISE(COORDS)
        COORDS1 = COORDS(1:NOPT)
        COORDS2 = COORDS(NOPT+1:2*NOPT)
      END DO

      IF (CHECK_CONVERGENCE(COORDS1, COORDS2)) EXIT
    END DO
  END SUBROUTINE BITSS


  FUNCTION BARRIER_ESTIMATE(COORDS1, COORDS2)
    DOUBLE PRECISION :: COORDS1(NOPT), COORDS2(NOPT)
    DOUBLE PRECISION :: BARRIER_ESTIMATE
    INTEGER :: I
    DOUBLE PRECISION :: EMIN, EMAX, T, COORDST(NOPT)

    EMIN = MAX(POT(COORDS1), POT(COORDS2))
    EMAX = - HUGE(EMAX)
    DO I = 1, 9
      T = I / 10
      COORDST = (1-T)*COORDS1 + T*COORDS2
      EMAX = MAX(EMAX, POT(COORDST))
    END DO
    BARRIER_ESTIMATE = EMAX - EMIN
  END FUNCTION BARRIER_ESTIMATE


  SUBROUTINE COMPUTE_COEF(COORDS1, COORDS2)
    USE KEY, ONLY : BITSSALPHA, BITSSBETA
    USE BITSS_POTENTIAL, ONLY : DISTANCE, KE, KD
    DOUBLE PRECISION, INTENT(IN) :: COORDS1(NOPT), COORDS2(NOPT)
    DOUBLE PRECISION :: EB, D, KD1, KD2, E, G1(NOPT), G2(NOPT), RMS

    EB = BARRIER_ESTIMATE(COORDS1, COORDS2)
    IF (EB <= 0) RETURN ! Do not update coefficients
    D = DISTANCE(COORDS1, COORDS2)
    CALL POTENTIAL(COORDS1, E, G1, .TRUE., .FALSE., RMS, .FALSE., .FALSE.)
    CALL POTENTIAL(COORDS2, E, G2, .TRUE., .FALSE., RMS, .FALSE., .FALSE.)

    KE = BITSSALPHA / (2 * EB)
    KD1 = SQRT(SUM(G1**2) + SUM(G2**2)) / (2.8284 * BITSSBETA * D)
    KD2 = EB / (BITSSBETA * D**2)
    KD = MAX(KD1, KD2)
  END SUBROUTINE COMPUTE_COEF


  FUNCTION CHECK_CONVERGENCE(COORDS1, COORDS2)
    USE KEY, ONLY : BITSSSTOP
    USE BITSS_POTENTIAL, ONLY : TARGET_DIST
    DOUBLE PRECISION :: COORDS1(NOPT), COORDS2(NOPT)
    LOGICAL :: CHECK_CONVERGENCE
    CHECK_CONVERGENCE = TARGET_DIST < BITSSSTOP
  END FUNCTION CHECK_CONVERGENCE


END MODULE BITSSMODULE
