MODULE KEY
      USE PREC, ONLY: REAL64
      IMPLICIT NONE
      SAVE


      INTEGER :: NSUMMARY, NADM, MSTEPS, BFGSSTEPS, NSTEPS, NVALUES, NVECTORS, EFSTEPS, NFREEZE, HINDEX, &
     &        FIXAFTER, NBOXTS, NREPELTS, REPELFROM, BHSTEPS, BHSTEPSMIN, KADJUSTFRQ, GUPTATYPE, &
     &        NDIIA, NINTV, NGRADIENTS, NZERO, NPOWER, NBFGSMAX1, NBFGSMAX2, MNBFGSMAX1, MNBFGSMAX2, PVSTEPS, &
     &        NEVL, NEVS, NHCHECK, NHUP=0, NSTHUP, INTHUP, XMUL, NSTEPMIN, LSYS, MUPDATE, XMUPDATE, &
     &        MMUPDATE, NEBMUPDATE, INTMUPDATE, FILTH, FILTH2, NFAILMAX, NPERMGROUP, GCIMAGE, GCSTEPS, GCUPDATE, GCSEED, &
     &        NUSEEV, PATHSDSTEPS, HMNEVS, HMNEVL, HMNSTEPS, HMNBFGSMAX1, HMNBFGSMAX2, &
     &        BBRM, BBRSTEPS, NORDER, NSECDIAG, STOCKMAXSPIN, BISECTSTEPS, BISECTMAXATTEMPTS, NEBRESEEDINT, NREPULSIVE, &
     &        NNREPULSIVE, NEBRESEEDPOW1, NEBRESEEDPOW2, NCONSTRAINT, NENDHESS, ACKLANDID, RBATOMSMAX, &
     &        DPID, TIPID, PAHID, PAPID, NCARBON, NTSITES, NRBGROUP, INTIMAGE, DUMPINTXYZFREQ, DUMPINTEOSFREQ, &
     &        NRBTRIES, REDOTSIM, REDOBFGSSTEPS, RPIMAGES, RPDOF, SDOXYGEN, SDHYDROGEN, SDCHARGE, BOWMANPES, &
     &        INTCONSEP, PATOM1, PATOM2, INTREPSEP, NCONSTRAINTON, CPREPSEP, CPCONSEP, NCONGEOM, &
     &        NCPREPULSIVE, NCPCONSTRAINT, MAXCONUSE, INTCONSTEPS, INTRELSTEPS, INTSTEPS1, INTLJSTEPS, &
     &        NTRAPPOW, MAXINTIMAGE, CHECKDID, CHECKREPINTERVAL, INTFREEZEMIN, INTNTRIESMAX, INTIMAGEINCR, &
     &        NCONSTRAINTFIX, INTIMAGECHECK, NREPULSIVEFIX, NRANROT, NENDDUP, LOCALPERMNEIGH, &
     &        LOCALPERMMAXSEP, NONEDAPBC, STRUC, &
     &        PMPATHINR, MULTISUNIT, MULTIFUNIT,NIMAGEINST,NGLJ,ST_TSSTEP,LANSTEP,NONFREEZE, &
     &        MCPATHBINS,MCPATHEQUIL,MCPATHSTEPS,MCPATHPRTFRQ,MCPATHTS,MCPATHSCHECK,RPHSLICES,RPHQBINS, &
     &        ITWIST, JTWIST, KTWIST, LTWIST, MCPATHSTART, MCPATHBLOCK, MCPATHOVER, NCPU, MCPATHDOBLOCK, MCMERGES, MCMERGEQ, &
     &        MCMERGEI,GAUSSIANCHARGE,GAUSSIANMULTI,ITG03, REDOTS, QCIPERMCHECKINT, &
     &        MLPIN, MLPSTART, MLPOUT, MLPHIDDEN, MLPDATA, NMLP, N_TO_ALIGN, DJWRBID, STM, NHEXAMERS, &
     &        MLSUPIN, MLSUPSTART, MLSUPOUT, MLSUPHIDDEN, MLSUPDATA, NMLSUP, MLSUPLAMBDA, MLPMINIMA, &
     &        MLQIN, MLQSTART, MLQOUT, MLQDATA, NMLQ, &
     &        QCIADDREP, QCIBONDS, QCISECOND, MAXNACTIVE, QCIIMAGE, NADDTARGET, NUMNN, MULTI_COUNT, MULTI_LAST, MULTI_STEP, &
     &        NDOF, RECCOUNT, MLPPROBPOS, PUSHOPTMAX, MLPNEIGH, QCICYCN, QCIPDINT, NPEAKS, NDISPLACEMENTS, NROTATIONS, &
     &        MAX_ANGMOM, BNB_NSTEPS, QUIPZ, QCIRESETINT1, QCIRESETINT2, JMAXCON, NCONOFF, QCIINTREPMINSEP, QCIKADJUSTFRQ, &
     &        NANCHOR, EWALDN, NPERMGROUPQCI, NPERMGROUPBACK, NEBREDISINT, NEBREALIGNINT, EOSUNIT, DLvars, &
     &        NROACH, NPAD, NBARRIER, QCMODE, DUMPSINTERVAL, MAXNSETS, MLCURRENTMIN, &
     &        N_FEATURES, N_POINTS, N_CLUSTERS, KMEANS_NP, QCIALIGNN, QCILINEARN, UCCMODE, QCINMDN, NIMAGEMORE, &
     &        NIMAGEREAD, INTIMAGENEW

      LOGICAL :: DTEST, MASST, RTEST, EFSTEPST, VECTORST, SUMMARYT, DUMPV, DUMPMAG, FREEZE, FREEZERANGE, GRADSQ, &
     &        PGRAD, VALUEST, ADMT, BFGSMINT, BFGSTST, CHECKINDEX, TOSI, CONTAINER, &
     &        GAUSSIAN, CADPAC, PRESSURE, FTEST, DCHECK, CP2K, DFTP, CPMD, CPMDC, FREEZERES, DF1T, &
     &        VARIABLES, FIELDT, OHT, IHT, TDT, D5HT, TWOENDS, PV, FRACTIONAL, BLNT, HYBRIDMINT, &
     &        INDEXT, LANCZOST, NOSHIFT, GAMESSUS, GAMESSUK, PVTS, RIGIDBODY, CASTEP, ONETEP, QCHEM, QCHEMES, VASP, &
     &        BFGSSTEP, EFOLSTEP, BULKT, HUPDATE, NOHESS, READV, NOIT, THOMSONT, SIO2T, SIO2C6T, BISECTT, BISECTDEBUG, &
     &        TOSIC6, TOSIPOL, FIXIMAGE, DFTBT, CHECKCONT, CHECKDT, SHIFTED, READSP, DUMPSP, NOFRQS, &
     &        ALLSTEPS, ALLVECTORS, MWVECTORS, WELCH, BINARY, READHESS, MOVIE, NORESET, TWOD, &
     &        DOUBLET, REOPT, PARALLEL, LINEMIN, FIXD, KEEPINDEX, BSMIN, PRINTPTS, RKMIN, REPELTST,&
     &        REPEL,UNRST, NATBT, ANGLEAXIS, DUMPALLPATHS, GOT, REOPTIMISEENDPOINTS, DUMPDATAT, MORPHT, PERMDIST, &
     &        GREATCIRCLET, DESMDEBUG, GROWSTRINGT, FREEZENODEST, STOCKT, BHINTERPT, BHDEBUG, CHRIGIDT, PERMDISTINIT, &
     &        BBRSDMT, AMBERT, NABT, DUMPSTRUCTURES, ORDERPARAMT, BHINTERPUSELOWEST, STOCKSPIN, LOWESTFRQT, PTSTSTT, &
     &        RBAAT, DBPT, DBPTDT, DMBLPYT, LWOTPT, GBT, GBDT, MSSTOCKT, NIMET, NCAPT, NTIPT, PAHAT, SILANET, &
     &        PAPT, PATCHYDT, PYGT, RADIFT, UNIAXT, STOCKAAT, EFIELDT, BHCHECKENERGYT, &
     &        REDUCEDBONDLENGTHT, CBT, CLOSESTALIGNMENT, NEBRESEEDT, ADDREPT, INTCONSTRAINTT, &
     &        LOCALPERMDIST, DOCROSSCHECK, REDOKADD, REDOPATH1, REDOPATH2, ANGLEAXIS2, ATOMMATCHDIST, ATOMMATCHINIT, &
     &        INSTANTONRATET,RINGPOLYMERT, SDT, BOWMANT, PULLT, RBSYMT, CONPOTT, GRAD4T, RPCYCLICT, RPFIXT, &
     &        CHECKCONINT, ATOMMATCHFULL, NIH2LEPST,NIHEAM7T,NIHLEPST, NIHPAIRONLYT, &
     &        QSPCFWT, QTIP4PFT, CFUSIONT, DUMPINTXYZ, DUMPINTEOS, INTLJT, INTTST, EYTRAPT, OHCELLT, MKTRAPT, &
     &        INTFREEZET, LPERMDIST, CHECKNEGATIVET, CHECKOVERLAPT, ACK1, ACK2, CONDATT, USERPOTT, &
     &        CONCUTFRACT, CONCUTABST, ENDNUMHESS2, CHARMMDFTBT, PAIRCOLOURT, REVERSEUPHILLT, WHOLEDNEB, &
     &        NONEBMAX, READMASST, ONEDAPBCT, ONEDPBCT, INVTONEDPBCT, INVTTWODPBCT, TWODAPBCT, TWODPBCT, THREEDAPBCT, &
     &        THREEDPBCT, FOURDAPBCT, FOURDPBCT, MODEDOWNT, CHEMSHIFT, TTM3T, &
     &        NOINVERSION, INVERTPT, KNOWVECS, PMPATHT, AAORIENTT, MULTIJOBT, QUIPARGSTRT, QUIPPARAMST, HESSDUMPT, &
     &        CLASSICALRATEST, TSPLITTINGT, HESSREADT, INSTANTONOPTT,INSTANTONSTARTDUMPT,VARSTEPOPTT, MOLPRO, REAXFFT, &
     &        EIGENONLY,OVERCONV, GLJT,CLSTRINGT,CLSTRINGTST, PHI4MODT, EX1DT, MCPATHT, MCBIAST, RPHT, TWISTT, MCPATH2T, &
     &        PBST, SSHT, GAUSSIAN03, GAUSSIAN09, CPPNEBT, CUDAT, CUDATIMET, TRUSTMODET,MODELOST, METRICTENSOR, INTSPRINGACTIVET, &
     &        PERMGUESS, QCIPERMCHECK, DUMPFRQST, MULTIPOTT, MLP3T, MLPB3T, DUMPBESTPATH, ALIGNRBST, AVOID_COLLISIONS, MLPPROB, &
     &        MALONALDEHYDE, SIO2PT, MLPNEWREG, DJWRBT, STEALTHYT, STEALTV, LJADDT, MLPB3NEWT, MLPVB3T, AUCMLPVB3T, MLPPRINT, &
     &        QCIPOTT, QCIPOT2T, QCIRADSHIFTT, QCINOREPINT, QCIAMBERT,QCISBT, SLERPT, NOTRANSROTT, MAXGAPT, BULKBOXT, GDSQT, &
     &        FLATTESTT, MLQT, MLQPROB, LJADD2T, MACROIONT, NOREGBIAS, PYADDT, PYADD2T, SANDBOXT, LJADD3T, LJCOULADD3T, LJADD4T, &
     &        MBPOLT, MULTIJOB_MACHINET, DUMPDATA_MACHINET, PLUSSIDET, MINUSSIDET, PUSHOPTT, MLPVB3NNT, GAUSSIAN16, QCICYCLEST, &
     &        QCIDNEBT, QCIRESTART, QCILPERMDIST, FASTOVERLAPT, BNB_ALIGNT, QUIPT, QCIADDACIDT, DOBACK, QCIRESET, DOBACKALL, &
     &        QCITRILAT, QCISTOP, QCILPDCON, GDMLT, RPPROJEXTRA, ANCHORT, CHECKGRADT, CHECKHESST, ANCHORTT, EWALDT, ORTHO, &
     &        CHARGEST, EWALDDEBUGT, BENZRIGIDEWALDT, PBETTER, QCIPERMT, NEBREDIST, DLT, MLSUPT, DOINVERSION, QiYuT, DUMPEVALST, &
     &        VASPCART,DFTBPT,RBCHECKSTOP,ROACHT, QCHEMSCFDUMP, NOCUDALBFGS, XTB, MLMINT, KMEANST, NEBSTOPT, DIHEDRALMETRICT, &
     &        NEBREALIGN, QCIHIRET,AUCMLPLOGT, NONUDGE, QCIALIGN, QCILINEARLIST, DNEBPATHT, KINTSCALET, NEBKSCALET, QCINMDT, SAMT, &
     &        QCIREADGUESS, QCIIMAGEDENST
      LOGICAL :: LPERMOFF=.FALSE.

! sy349 > for testing the flatpath after dneb
      !LOGICAL, ALLOCATABLE :: FLATPATHT(:)
      LOGICAL FLATPATHT

! bf269 > polymer in a pore (non-bonding (LJ) energy from neighbours is not subtracted)
      LOGICAL :: PORE8T = .FALSE. ! add 8th power cylindrical pore to the potential?
      INTEGER :: PORE8_AXIS = 3 ! principal axis of the cylindric pore (1:x, 2:y, 3:z)
      DOUBLE PRECISION :: PORE8_ENERGY = 1.0d1 ! energy of the pore when radius = 1
      LOGICAL :: HARMPOLYT = .FALSE. ! add harmonic bonds between the beads
      DOUBLE PRECISION :: HARMPOLY_BONLEN = 0.0d0 ! equilibrium length of springs between beads
      DOUBLE PRECISION :: HARMPOLY_K = 1.0d2 ! force constant of the springs

! hk286 > generalised THOMSON problem
      LOGICAL :: GTHOMSONT, GTHOMWRAPT
      DOUBLE PRECISION :: GThomsonZ, GThomsonC, GThomsonC2, VUNDULOID,GTHOMSONBIND
      DOUBLE PRECISION :: GTrefU, GTrefZ, GTmu, GTk, GTm, GTn, GTa, GTc
      INTEGER :: GTHOMMET, NGTHORI, GTHOMPOT, GTHOMSONBINN, GThomsonBinaryN
      DOUBLE PRECISION :: GThomsonSigma, GThomsonRho, GThomsonSigma1, GThomsonSigma2
! jp908> Gthomson binary yukawa terms
      DOUBLE PRECISION :: GThomsonRepul, GThomsonYukawa, GThomsonCharge1, GThomsonCharge2

      LOGICAL :: MACHINE=.FALSE., NEBMIND=.TRUE.

      DOUBLE PRECISION :: TRAD, RESIZE, JZ, PUSHOFF, TOLD, TOLE, PCUT, DAMP, RADIUS, TWOEVAL, PVCONV, PVTOL, &
     &        OMEGA, GALPHA, MALPHA1, FOH, FIH, FTD, FD5H, T12FAC, PRESS, MAXERISE, RK_R, RK_THETA, &
     &        CONVU, CONVR, SYMCUT, MXSTP, GFRACTION, CEIG, REPELPUSH, XMAXERISE, GCCONV, NEBK, &
     &        MFRACTION1, MFRACTION2, MALPHA2, ACCLAN, SHIFTLAN, CUTLAN, GMAX, EVCUT, NEBDGUESS, INTDGUESS,  &
     &        MINMAX, MAXMAX, C6PP, C6MM, C6PM, PUSHCUT, MAXBFGS, MAXXBFGS, MAXMBFGS, MAXNEBBFGS, MAXINTBFGS, &
     &        APP, AMM, APM, XQP,XQM, ALPHAP, ALPHAM, PHIG, SHIFTV, DGUESS, XDGUESS, TIMELIMIT, TSTART, &
     &        INTEPSILON, FRAMEEDIFF, MORPHERISE, MORPHEMAX, MORPHMXSTP, MAXTSENERGY, MAXBARRIER, GCMXSTP, GCSCALE, &
     &        FREEZETOL, DESMAXEJUMP, DESMAXAVGE, STOCKMU, STOCKLAMBDA, EDIFFTOL, GEOMDIFFTOL, DNEBSWITCH, &
     &        BHACCREJ, BHSTEPSIZE, BHCONV, BHTEMP, BHDISTTHRESH, BHMAXENERGY, BHK, DIJKSTRALOCAL, KADJUSTFRAC, KADJUSTTOL, &
     &        BHSFRAC, HMCEIG, HMMXSTP, HMEVMAX, BBRGAM, BBREPS, BBRSIGMA1, BBRSIGMA2, BBRALPHA, BBRCONV, STOCKZTOL, &
     &        GBKAPPA, GBKAPPRM, GBMU, GBNU, GBSIGNOT, GBEPSNOT, GBCHI, GBCHIPRM, KADJUSTMIN, KADJUSTMAX, &
! adk44
     &        CAPSIDRHO, CAPSIDEPS, SIGMAPENT, RADPENT, RADHEX, SIGMAHEX, SIGMAPH, &
     &        PYA1(3), PYA2(3), PYSIGNOT, PYEPSNOT, NEBKINITIAL, NEBKFINAL, NEBFACTOR, &
     &        DBEPSBB, DBEPSAB, DBSIGBB, DBSIGAB, DBPMU, YEPS, YKAPPA, MAXMAXBARRIER, PAPALP, PAPEPS, PAPS, PAPCD, &
     &        RHOCC0, RHOCC10, RHOCC20,  RHOHH0, RHOHH10, RHOHH20, RHOCH0, RHOC10H, RHOCH10, RHOC20H, RHOCH20, &
     &        EPS11, EPS22, EPS12, MRHO, MRHO11, MRHO22, MRHO12, REQ11, REQ22, REQ12, &
     &        ALPHACC, ALPHAHH, ALPHACH, DC6CC, DC6HH, DC6CH, KKJ, CCKJ, KINT, KINTUSE, KINTENDS, &
     &        LPDGEOMDIFFTOL, INTCONFRAC, MAXCONE, INTRMSTOL, BFGSTSTOL, ORBITTOL, EVPC, &
     &        BISECTMAXENERGY, BISECTMINDIST, BLFACTOR, NEBRESEEDEMAX, NEBRESEEDBMAX, NEBRESEEDDEL1, &
     &        NEBRESEEDDEL2, INTCONSTRAINTTOL, INTCONSTRAINTDEL, RBCUTOFF, INTCONSTRAINTREP, INTCONSTRAINREPCUT, &
     &        REDOK, REDOFRAC, D1INIT, D2INIT, REDOE1, REDOE2, RPBETA, REPCON, PFORCE, &
     &        CPCONSTRAINTTOL, CPCONSTRAINTDEL, CPCONSTRAINTREP, CPCONSTRAINREPCUT, CPCONFRAC, &
     &        INTLJTOL, INTLJDEL, INTLJEPS, IMSEPMIN, IMSEPMAX, TRAPK, MINOVERLAP, &
     &        INTFREEZETOL, LOCALPERMCUT, LOCALPERMCUT2, LOCALPERMCUTINC, CHECKREPCUTOFF, CONCUTABS, CONCUTABS2, &
     &        CONCUTFRAC, ENDNUMHESSDELTA, DNEBEFRAC, QCHEMSCALE, KAA, SIGMAAA, QUIPATOMMASS, TEMPERATURE1, &
     &        DISTORTINST,DELTAINST,MOLPROSCALE,COVER,STTSRMSCONV,LAN_DIST,LANCONV,LANFACTOR, &
     &        STOCKEXP, JPARAM, MCPATHTEMP, MCPATHDMAX, MCPATHSTEP, MCPATHACCRATIO, BIASFAC, &
     &        MCADDDEV, MCPATHQMIN, MCPATHQMAX, RPHQMIN, RPHQMAX, RPHTEMP, TWISTF, TWISTREF, MCPATHADDREF, &
     &        MCPATHGWS, MCPATHGWQ, MCPATHNEGLECT, MCPATHTOL, FRAMESDIFF,TMRATIO, INTMINFAC, MLPLAMBDA, COLL_TOL, KLIM, SCA, &
     &        NEBMAXERISE, GDSQ, FLATEDIFF, QCIADDREPCUT, QCIADDREPEPS, QCIRADSHIFT, INTCONCUT, MLQLAMBDA, FRQCONV, FRQCONV2, &
     &        TANHFAC, LJADDCUTOFF,LJADDREFNORM,MAXIMFACTOR, PUSHOPTCONV, QCICYCDIST, QCIPERMCUT, KERNELWIDTH, QUIPLATT(3,3), &
     &        ECON, EREP, ESPRING, CONVERGECONTEST, CONVERGEREPTEST, FCONTEST, FREPTEST, QCIKADJUSTTOL, QCIKADJUSTFRAC, QCIAVDEV, &
     &        QCIKINTMAX, QCIKINTMIN, ANCHORLAMBDA, CHECKDIFF, TCOEFF, EWALDALPHA, EWALDREALC, EWALDRECIPC, RSPEED, &
     &        PDISTANCE, NOPDISTANCE, NEBKALPHA, RBCHECKTOL, REPS1, RRHO1, RRE1, REPS2, RRHO2, RRE2, KMEANS_B, KINTSCALED, RHOSAM, &
     &        IMDENSITY

      CHARACTER(LEN=20) :: GAUSSGUESS='HUCKEL'
      CHARACTER(LEN=100) :: PATHINFODIR=''
      CHARACTER(LEN=100) :: QCIGUESSFILE

!     sf344
      DOUBLE PRECISION :: PCUTOFF,PYA11(3),PYA21(3),PYA12(3),PYA22(3),PEPSILON1(3),PSCALEFAC1(2),PSCALEFAC2(2), &
     &                     PEPSILONATTR(2),PSIGMAATTR(2), PYOVERLAPTHRESH, LJSITECOORDS(3), LJGSITESIGMA, LJGSITEEPS, &
     &                     PYLOCALSTEP(2),PYCFTHRESH,PYGRAVITYC1,PYGRAVITYC2,PERCCUT

      DOUBLE PRECISION, ALLOCATABLE :: PYADDEPS(:,:)
      DOUBLE PRECISION, ALLOCATABLE :: SHIFTL(:)
      LOGICAL, ALLOCATABLE :: UNIAXARRAY(:)
      DOUBLE PRECISION, ALLOCATABLE :: PYADDREP(:,:), PYADDATT(:,:)
      DOUBLE PRECISION, ALLOCATABLE :: POINTSDECA(:), POINTSICOS(:)
      DOUBLE PRECISION, ALLOCATABLE :: VT(:), PYA1BIN(:,:), PYA2BIN(:,:), SITE(:,:)
      LOGICAL          :: LJSITE,BLJSITE,LJSITEATTR,PYBINARYT,PARAMONOVPBCX,PARAMONOVPBCY,PARAMONOVPBCZ,PARAMONOVCUTOFF
      LOGICAL          :: PYGPERIODICT,ELLIPSOIDT,LJSITECOORDST,REALIGNXYZ,MULTISITEPYT,LJGSITET,NORMALMODET,PYT,PYCOLDFUSION
      INTEGER          :: MAXINTERACTIONS,PYBINARYTYPE1,MYUNIT,NPYSITE
      DOUBLE PRECISION :: GBANISOTROPYR, GBWELLDEPTHR
!     CHRIS
!     MCP
      LOGICAL :: AMHT
      CHARACTER(LEN=3) :: RES_TYPE_ALA='ALA'
      CHARACTER(LEN=5) :: TARFL
      CHARACTER(LEN=120) :: CASTEPJOB, CP2KJOB, ONETEPJOB, QCHEMJOB, VASPJOB, MULTISTART, MULTIFINISH,MOLPROJOB,REAXFFJOB
      CHARACTER(LEN=120) :: XTBSYS, XTBJOB
      CHARACTER(LEN=30) :: QCHEMJOBPARAMS=''
      CHARACTER(LEN=30) :: MOLPROJOBPARAMS=''
      CHARACTER(LEN=30) :: KMEANS_FILE
      CHARACTER(LEN=5) :: RPSYSTEM

      INTEGER :: SEQ(500),NUMGLY
      DOUBLE PRECISION :: FINCORD(150,3,3,3)
      INTEGER :: NRES_AMH_TEMP

      INTEGER PROCNT, FINNMRSS, FINNUMCRR, FINNUMPRR, FINNQUENCH

      CHARACTER(LEN=80) :: SYS, FILTHSTR, BOWMANDIR
      CHARACTER(LEN=20) :: EDITIT
      CHARACTER(LEN=4) :: NPROC
      CHARACTER(LEN=2) :: HMMETHOD
      CHARACTER(200) :: CPMD_COMMAND
      LOGICAL :: SCORE_QUEUE
      DOUBLE PRECISION :: EFIELD  ! ELECTRIC FIELD, EFIELD, IN THE Z-DIRECTION
      DOUBLE PRECISION :: COLDFUSIONLIMIT
      LOGICAL, ALLOCATABLE, DIMENSION(:) :: FROZEN, FROZENRES, INTFROZEN  !  MXATMS
      DOUBLE PRECISION, ALLOCATABLE :: ANCHORCOORDS(:,:)
      INTEGER, ALLOCATABLE :: NPERMSIZE(:), PERMGROUP(:), ORDERNUM(:)
      INTEGER, ALLOCATABLE :: NPERMSIZEQCI(:), PERMGROUPQCI(:)
      INTEGER, ALLOCATABLE :: NPERMSIZEBACK(:), PERMGROUPBACK(:)
      INTEGER, ALLOCATABLE :: NSETS(:)
      INTEGER, ALLOCATABLE :: SETS(:,:,:)
      INTEGER, ALLOCATABLE :: NSETSQCI(:), NSETSBACK(:)
      INTEGER, ALLOCATABLE :: SETSQCI(:,:,:), SETSBACK(:,:,:)
      INTEGER,ALLOCATABLE,DIMENSION(:) :: NGLJSPECIES       ! for GLJ
      DOUBLE PRECISION, ALLOCATABLE :: GLJEPS(:,:), GLJSIG(:,:) ! GLJ parameters
      DOUBLE PRECISION, ALLOCATABLE, DIMENSION(:) :: CHARGE  !  3*MXATMS
      DOUBLE PRECISION, ALLOCATABLE, DIMENSION(:,:) :: REPELTS  !  3*MXATMS,100
      DOUBLE PRECISION ,ALLOCATABLE :: LJREP_BLN(:,:), LJATT_BLN(:,:), A_BLN(:), B_BLN(:), C_BLN(:), D_BLN(:)
      CHARACTER(LEN=1), ALLOCATABLE :: BEADLETTER(:), BLNSSTRUCT(:)
      CHARACTER(LEN=4), ALLOCATABLE :: WHICHORDER(:)
      INTEGER :: NREPMAX=10, NCPREPMAX=10
      INTEGER :: INTCONMAX=10, NCPCONMAX=10
      DOUBLE PRECISION, ALLOCATABLE :: EPSALPHA(:), DISTREF(:)
      DOUBLE PRECISION, ALLOCATABLE :: CPDISTREF(:)
      DOUBLE PRECISION, ALLOCATABLE :: MIN1REDO(:), MIN2REDO(:)
      DOUBLE PRECISION, ALLOCATABLE :: CONDISTREF(:), CONDISTREFLOCAL(:), CONDISTREFON(:), CONDISTREFLOCALON(:)
      DOUBLE PRECISION, ALLOCATABLE :: CONCUT(:), CONCUTLOCAL(:)
      DOUBLE PRECISION, ALLOCATABLE :: CONDISTREFFIX(:), CONCUTFIX(:)
      DOUBLE PRECISION, ALLOCATABLE :: CPCONDISTREF(:)
      DOUBLE PRECISION, ALLOCATABLE :: INTNEBIMAGES(:)
      DOUBLE PRECISION, ALLOCATABLE :: CONGEOM(:,:)
      DOUBLE PRECISION, ALLOCATABLE :: LJADDEPS(:,:)
      DOUBLE PRECISION, ALLOCATABLE :: LJADDREP(:,:), LJADDATT(:,:)
      DOUBLE PRECISION, ALLOCATABLE :: COUL_SIGMA0(:,:), COUL_KQQ(:,:)
      DOUBLE PRECISION              :: LJCOULADD3RESTRAINTK, LJCOULADD3RESTRAINTR
      LOGICAL, ALLOCATABLE :: CONACTIVE(:), RESTRAINTARRAY(:)
      LOGICAL, ALLOCATABLE :: ATOMACTIVE(:)
      INTEGER, ALLOCATABLE :: NITSTART(:)
      DOUBLE PRECISION, ALLOCATABLE :: RPMASSES(:), XMINA(:), XMINB(:)
      DOUBLE PRECISION, ALLOCATABLE :: RBOPS(:,:)
      DOUBLE PRECISION, ALLOCATABLE :: SAVES(:), SAVEF(:)
!     LOGICAL, ALLOCATABLE :: CONTEST(:,:)
      INTEGER, ALLOCATABLE :: ORDERI(:), ORDERJ(:), REPPOW(:)
      INTEGER, ALLOCATABLE :: CONI(:), CONJ(:), CONION(:), CONJON(:), CONOFFLIST(:)
      LOGICAL, ALLOCATABLE :: CONOFFTRIED(:)
      INTEGER, ALLOCATABLE :: CONIFIX(:), CONJFIX(:), REPIFIX(:), REPJFIX(:)
      INTEGER, ALLOCATABLE :: REPI(:), REPJ(:)
      INTEGER, ALLOCATABLE :: CPCONI(:), CPCONJ(:)
      INTEGER, ALLOCATABLE :: CPREPI(:), CPREPJ(:)
      DOUBLE PRECISION, ALLOCATABLE :: REPCUT(:), NREPCUT(:), CPREPCUT(:), REPCUTFIX(:)
      INTEGER, ALLOCATABLE :: NREPI(:), NREPJ(:)
      INTEGER, ALLOCATABLE :: BESTPERM(:)
      INTEGER, ALLOCATABLE :: RBGROUP(:), RBNINGROUP(:)
      INTEGER, ALLOCATABLE :: TO_ALIGN(:)
      LOGICAL :: SETCHIRAL=.FALSE.
!BLN/Go parameters
      LOGICAL :: GOTYPE=.FALSE.
      DOUBLE PRECISION :: GOFACTOR=0D0
! Single ended TS search dihedral twisting
      DOUBLE PRECISION :: PSRANDOM
      INTEGER :: NTWISTABLE
      INTEGER, ALLOCATABLE :: DIHETOTWIST(:)
! ONEDAPB
      DOUBLE PRECISION, ALLOCATABLE     :: XYPHI(:)
!
! Macrocycle stuff
!
      LOGICAL :: MACROCYCLET = .FALSE.
      INTEGER :: MCYCLEREPEATS=1 !Number of repeat units in macrocycle
      INTEGER :: MCYCLEPERIOD !Length of repeat units in macrocycle (should be NATOMS/MCYCLEPERIOD)

! periodic boundary conditions
      DOUBLE PRECISION BULK_BOXVEC(3)
      DOUBLE PRECISION POTENTIAL_CUTOFF
      LOGICAL CUTT

! Variable box parameters
      LOGICAL :: BOXDERIVT
      DOUBLE PRECISION :: BOX_PARAMS(6), BOX_PARAMSGRAD(6)

! dj337: Ewald summation variables
      DOUBLE PRECISION, ALLOCATABLE, DIMENSION(:,:,:) :: RERHOARRAY, IMRHOARRAY

!QUIP variables
      CHARACTER(LEN=10240) :: QARGSTR
      CHARACTER(LEN=3) :: QUIPATOMTYPE

! js850> soft sphere potential
      DOUBLE PRECISION, ALLOCATABLE :: SOFT_SPHERE_RADII(:)

!fh301>{{{
      TYPE DIHEDRALPAR
        CHARACTER(LEN=4)  ATYPE
        CHARACTER*8       DIANGLE
        INTEGER           ATYPEID,DIANGLEID
        REAL(KIND=REAL64) P1,P2,P3,P4,P5
      END TYPE DIHEDRALPAR
      TYPE RESIDUE
        CHARACTER(LEN=4)  RES
        INTEGER           RESID
        REAL(KIND=REAL64) HA,CA,HN,N,CS,CB,NCORR,NCORR2
      END TYPE RESIDUE
      TYPE ONERES
        CHARACTER(LEN=4)  ATYPE
        CHARACTER(LEN=3)  POS
        INTEGER           ATYPEID,POSID
        REAL(KIND=REAL64) HA,CA,HN,N,CS,CB
      END TYPE ONERES
      TYPE ONEATOM
        CHARACTER*8       ATYPE
        CHARACTER(LEN=4)  RES
        INTEGER           RESID,ATYPEID
        REAL(KIND=REAL64) HA,CA,HN,N,CS,CB
      END TYPE ONEATOM
      TYPE ONEANGLE
        CHARACTER*8       ANGLE
        REAL(KIND=REAL64) HA,CA,HN,N,CS,CB
      END TYPE ONEANGLE
      TYPE ONERESPAR
        CHARACTER(LEN=4)  ATYPE
        CHARACTER(LEN=3)  POS
        CHARACTER(LEN=10) PARAM
        REAL(KIND=REAL64) HA,CA,HN,N,CS,CB
      END TYPE ONERESPAR
      TYPE TWORES
        CHARACTER(LEN=4)  ATYPE1,ATYPE2
        CHARACTER(LEN=3)  POS1,POS2
        INTEGER           ATID1,ATID2,POSID1,POSID2
        REAL(KIND=REAL64) HA,CA,HN,N,CS,CB
      END TYPE TWORES
      TYPE TDERIVATIVE
        TYPE(TDERIVATIVE), POINTER :: NEXT
        TYPE(TDERIVATIVE), POINTER :: PREVIOUS
        REAL(KIND=REAL64) :: D(3)
        INTEGER :: ATOM1,ATOM2
      END TYPE TDERIVATIVE
      TYPE TDERIVATIVEDIHEDRAL
        TYPE(TDERIVATIVEDIHEDRAL), POINTER :: NEXT
        TYPE(TDERIVATIVEDIHEDRAL), POINTER :: PREVIOUS
        REAL(KIND=REAL64) :: D(3)
        INTEGER :: ATOM
      END TYPE TDERIVATIVEDIHEDRAL
      TYPE TPOINTERS
        TYPE(TDERIVATIVE), POINTER :: LIST=> NULL()
        TYPE(TDERIVATIVE), POINTER :: FIRST=> NULL()
        TYPE(TDERIVATIVE), POINTER :: LAST=> NULL()
      END TYPE TPOINTERS
      REAL(KIND=REAL64) :: ENERGYCAMSHIFT, FULLENERGY, CSN, CSALPHA
      REAL(KIND=REAL64), DIMENSION(6) :: RMSSHIFT
      REAL(KIND=REAL64), DIMENSION(3,7)  :: HYDROPAR
      REAL(KIND=REAL64), ALLOCATABLE :: OBSCHEMSHIFT(:,:),ENERGYCAM(:), SHIFTDIF(:)
      REAL(KIND=REAL64), ALLOCATABLE :: FORCEX(:), FORCEY(:), FORCEZ(:)
      LOGICAL COUT
      CHARACTER(LEN=200) :: SVNROOT, CSPATH, SHIFTFILE
      CHARACTER(LEN=10) :: CSVERSION
      TYPE(DIHEDRALPAR) :: DIHED(18)
      TYPE(RESIDUE) :: RANCOIL(20)
      TYPE(ONERES) :: BACKBONEOTH(16),BACKBONEGLY(16),BACKBONEPRO(16)
      TYPE(ONEATOM) :: SIDECHAINOTH(195),SIDECHAINGLY(1),SIDECHAINPRO(9)
      TYPE(ONEATOM) :: HYBSP21(3),HYBSP22(3),HYBSP31(5),HYBSP32(5)
      TYPE(ONEATOM) :: HYBSP21OTH(3),HYBSP22OTH(3),HYBSP31OTH(5)
      TYPE(ONEATOM) :: HYBSP32OTH(5),HYBSP21GLY(3),HYBSP22GLY(3)
      TYPE(ONEATOM) :: HYBSP31GLY(5),HYBSP32GLY(5),HYBSP21PRO(3)
      TYPE(ONEATOM) :: HYBSP22PRO(3),HYBSP31PRO(5),HYBSP32PRO(5)
      TYPE(RESIDUE) :: RINGTYPEOTH(5),RINGTYPEGLY(5),RINGTYPEPRO(5)
      TYPE(ONEANGLE) :: DIHEANGOTH(3),DIHEANGGLY(3),DIHEANGPRO(3)
      TYPE(ONERESPAR) :: HYDROGENOTH(12),HYDROGENGLY(12),HYDROGENPRO(12)
      TYPE(TWORES) :: DISULFID,EXTDISOTH(26),EXTDISGLY(26)
      TYPE(TWORES) :: EXTDISPRO(26)


!     cjf41 collagen order parameter
      LOGICAL :: COLLAGENOP
      INTEGER :: COLLINDICES(4)

!Character string for CUDA potential
      CHARACTER(LEN=1) :: CUDAPOT

      !ds656> Mie field(s) for modelling substrate effects
      LOGICAL :: MIEFT, MIEF_CUTT, MIEF_PBCT
      CHARACTER(LEN=130) :: MIEF_FILENAME
      INTEGER :: MIEF_NSITES,MIEF_N,MIEF_M
      DOUBLE PRECISION :: MIEF_BOX(3), MIEF_RCUT
      DOUBLE PRECISION, ALLOCATABLE :: MIEF_EPS(:), MIEF_SIG(:), &
           MIEF_SITES(:,:), MIEF_U_RCUT(:), MIEF_DUDR_RCUT(:)

      DOUBLE PRECISION, ALLOCATABLE ::  QCIXYZ(:)
! AMBER 12 and 20 variables
      LOGICAL :: AMBER12T, AMBER20T
      LOGICAL :: CHIRALENDPOINTS, A12DECOMPT, A12DECOMPALLT, A20DECOMPT, A20DECOMPALLT
      INTEGER, DIMENSION(:,:), ALLOCATABLE :: BONDS
      INTEGER, DIMENSION(:), ALLOCATABLE :: ATOMSTORES

!
! DL data etc.
!
      DOUBLE PRECISION,ALLOCATABLE :: DLDATA(:,:), DLXS(:,:)
      INTEGER, ALLOCATABLE :: DLYS(:,:)
      INTEGER DLHIDDEN
      INTEGER,ALLOCATABLE,DIMENSION(:) :: LAYERS_WIDTH, N_HIDDEN       ! number of nodes in each layer, number of hidden nodes

      DOUBLE PRECISION, ALLOCATABLE ::  MLPDAT(:,:)
      INTEGER, ALLOCATABLE ::  MLPOUTCOME(:)
      INTEGER, ALLOCATABLE ::  MLSUPOUTCOME(:)
      DOUBLE PRECISION, ALLOCATABLE ::  MLMINWEIGHTS(:,:)
      DOUBLE PRECISION, ALLOCATABLE ::  MLQDAT(:,:)
      INTEGER, ALLOCATABLE ::  MLQOUTCOME(:)
      INTEGER, ALLOCATABLE ::  LJADDNN(:,:)
      INTEGER, ALLOCATABLE ::  COMMONCON(:,:), NCONCOMMON(:)
      REAL(KIND = REAL64), ALLOCATABLE ::  MINPROBS(:,:,:)
      INTEGER, ALLOCATABLE ::  MLPBESTMIN(:)

! ctc43> variable storing which surrogate function to use with the AUCMLPVB3 potential
      INTEGER :: AUCSURROGATE
      ENUM, BIND(C)
         ENUMERATOR :: AUCSIGMOID, AUCTANH, AUCHINGE, AUCEXP, AUCQUAD, AUCCUBIC
      END ENUM

      ! OPEP+HIRE interface
      LOGICAL :: OPEPT=.FALSE.
      LOGICAL :: OPEPHIRE_DEBUG = .FALSE.
     ! INTEGER :: HIREOPEP_VERSION
      ! HiRE library
      LOGICAL :: HIRET=.FALSE.


! Titrations for HiRE
      LOGICAL :: TITRATION = .FALSE.      !Tritration steps?
      INTEGER :: TITMETHOD = 1            !which method
      INTEGER :: TITNSTEPS = 100          !frequency of steps applied
      REAL(KIND = REAl64) :: PH = 7.0     !PH value used for titration

! HB for HiRE
      LOGICAL           :: RNAHBT = .FALSE.          !detect h-bonds and save
      LOGICAL           :: HBSAVET = .FALSE.         !save h-bonds at step
      INTEGER           :: HBNSTEPS = 1              !frequency for saving h-bonds

! SAXS for HiRE
      LOGICAL           :: SAXST = .FALSE.           !use SAXS
      INTEGER           :: SAXSNSTEPS = 1            !frequency for applying SAXS
      LOGICAL           :: SAXSFORCET = .FALSE.      !compute SASX force at MC transition?
      LOGICAL           :: SAXSMODULT = .FALSE.      !modulate SAXS force with decreasing and periodic factor?
      REAL(KIND=REAL64) :: SAXSINVSIG = 2.5          !broadness of the periodic modulation
      REAL(KIND=REAL64) :: SAXSWAVE = 100.0          !length of the decreasing modulation
      REAL(KIND=REAL64) :: SAXSOFFI = 0.0D0          !step variable for periodic modulation
      REAL(KIND=REAL64) :: SAXSMODI = 1.0D0          !step variable for decreasing modulation
      LOGICAL           :: SAXSPRINT = .FALSE.       !print curves and scores to unit
      INTEGER           :: SAXSNPRINT = 100          !frequency for printing SAXS
      LOGICAL           :: SAXSSAVET  = .FALSE.      !save computed SAXS at MC transition?
      REAL(KIND=REAL64) :: SAXSMAX = 1.0             !max value for SAXS vector
      LOGICAL           :: SAXSSOLT = .FALSE.        !vacuum (false) or solution (true) calculation
      LOGICAL           :: REFINET = .FALSE.         !refine hydration
      INTEGER           :: NWATLAY = 1               !number of hydration layers
      REAL(KIND=REAL64) :: WATRAD = 2.55             !water radius
      REAL(KIND=REAL64) :: WATW = 0.037              !water contrast


! NEWREAXFF variables
      LOGICAL :: NEWREAXFFT
! DFTBP variables
      !CHARACTER(LEN=*), DIMENSION(NATOMS) :: AtomSym

!Orbital variable
      LOGICAL :: ORBITALS
      INTEGER :: NROTS, NORBS, ORBVAREXPONENT
      DOUBLE PRECISION, ALLOCATABLE :: R2INTS(:,:), DIPINTS(:,:,:)
!
! QCHEM_SCF
!
      LOGICAL :: QCHEMSCF, QCHEMGHF
      INTEGER :: QCHEMESNAO, QCHEMESNMO, QCHEMESNELEC, QCHEMESNALPHA, QCHEMESNBETA, QCHEMESNZERO
      DOUBLE PRECISION, ALLOCATABLE :: KSAVE(:) ! to save steps for printing and path length
!    UHF specific
      DOUBLE PRECISION, ALLOCATABLE :: QCCOEFFA(:,:), QCCOEFFB(:,:), QCCOEFFASAVE(:,:), QCCOEFFBSAVE(:,:)
      DOUBLE PRECISION, ALLOCATABLE :: QCCOEFFAFIN(:,:), QCCOEFFBFIN(:,:) ! for double-ended searches
      DOUBLE PRECISION, ALLOCATABLE :: QCCOEFFATS(:,:), QCCOEFFBTS(:,:)
      DOUBLE PRECISION, ALLOCATABLE :: QCCOEFFAPLUS(:,:), QCCOEFFBPLUS(:,:)
      DOUBLE PRECISION, ALLOCATABLE :: QCCOEFFAMINUS(:,:), QCCOEFFBMINUS(:,:)
!    GHF specific
      DOUBLE PRECISION, ALLOCATABLE :: QCCOEFFG(:,:), QCCOEFFGSAVE(:,:)
      DOUBLE PRECISION, ALLOCATABLE :: QCCOEFFGFIN(:,:) ! for double-ended searches
      DOUBLE PRECISION, ALLOCATABLE :: QCCOEFFGTS(:,:), QCCOEFFGPLUS(:,:), QCCOEFFGMINUS(:,:)
!
!  count QCHRM calls for input file adjustment
!
      INTEGER :: QCHEMCALLS=0
!
! UCC and UCCGBH
!
      LOGICAL :: UCC, UCCGBH, UCCPERIODIC, UCCPRINT
      INTEGER :: UCCNOPS, UCCDIM
      DOUBLE PRECISION, ALLOCATABLE :: UCCAMP(:), UCCHAM(:,:), UCCOPS(:,:,:)
!
! For UCC GBH runs we need the operator order
!
      INTEGER, ALLOCATABLE :: UCCOPORDER(:)

!
! Variables for distance constraint potential
!
      INTEGER NDISTCON
      INTEGER, ALLOCATABLE :: CONDISTATOM1(:), CONDISTATOM2(:)
      DOUBLE PRECISION, ALLOCATABLE :: CONDIST(:), KDIST(:)

! jp908> Variables for the phase-field binary wetting potential PFWETBIN
      LOGICAL :: PFWETBINT
      INTEGER :: GRIDX, GRIDY, GRIDZ, PFCONSTVOL, PFINITTYPE
      INTEGER :: NPOSTX, NPOSTY, WIDTHX, WIDTHY, TOPEXX, TOPEXY, HEIGHT1, HEIGHT2, LIPX, LIPY, LIPZ
      REAL(KIND = REAL64) :: PFPRESSURE, PFEPSILON, PFGRIDSIZE, PFCM1, PFV0, PFCVOL, PFCA1
      INTEGER, ALLOCATABLE :: NODESTATE(:), NEIGHBS(:,:), PAIRSTATE(:,:), GSQCASE(:,:)
      REAL(KIND = REAL64), ALLOCATABLE :: NODEWEIGHT(:), SURFWEIGHT(:), WETENERGY(:), WETTYPE(:)
      LOGICAL :: XSWITCH, YSWITCH, ZSWITCH

! kr366> added variables to apply a pulling force at multiple sites
      INTEGER, ALLOCATABLE :: PMULTA1(:), PMULTA2(:)   !list of atoms to be pulled, corrsponding to PATOM1 aqnd PATOM2
      INTEGER :: NPULL=0                               !number of constraints
      LOGICAL :: MULTIPULLT=.FALSE.
      DOUBLE PRECISION, ALLOCATABLE :: PMULTFRC(:)     !list of applied forces

! mpn26> added for AUC_MLPVB3
      REAL(KIND = REAL64) :: AUCMLPBETA, AUCMLPBETAMAX

! kr366> OPEP and HiRE QCI setup
      INTEGER :: NBONDSOPEP = 0
      INTEGER, ALLOCATABLE :: BONDSOPEP(:,:)

! dw34> atoms to align or linear interp for QCI
      INTEGER, ALLOCATABLE :: QCIALIGNATOMS(:), QCILINEARATOMS(:)

! SJA> variables for BITSS transition state search
      LOGICAL :: BITSST
      INTEGER :: BITSSMAXITER, BITSS_COEFITER
      REAL(KIND = REAL64) :: BITSSSTEP, BITSSSTOP, BITSSALPHA, BITSSBETA
! DEMAX, Convergence, m (histsize), max_iter
      INTEGER :: BITSSLBFGS_m, BITSSLBFGS_maxiter
      REAL(KIND = REAL64) :: BITSSLBFGS_dEmax, BITSSLBFGS_conv,  BITSSLBFGS_maxstep

CONTAINS

      ! jwrm2> Deallocates all allocatable arrays in KEY module.
      SUBROUTINE KEY_DEALLOCATE()

         IMPLICIT NONE

         IF (ALLOCATED(PYADDEPS)) DEALLOCATE(PYADDEPS)
         IF (ALLOCATED(SHIFTL)) DEALLOCATE(SHIFTL)
         IF (ALLOCATED(UNIAXARRAY)) DEALLOCATE(UNIAXARRAY)
         IF (ALLOCATED(PYADDREP)) DEALLOCATE(PYADDREP)
         IF (ALLOCATED(PYADDATT)) DEALLOCATE(PYADDATT)
         IF (ALLOCATED(POINTSDECA)) DEALLOCATE(POINTSDECA)
         IF (ALLOCATED(POINTSICOS)) DEALLOCATE(POINTSICOS)
         IF (ALLOCATED(VT)) DEALLOCATE(VT)
         IF (ALLOCATED(PYA1BIN)) DEALLOCATE(PYA1BIN)
         IF (ALLOCATED(PYA2BIN)) DEALLOCATE(PYA2BIN)
         IF (ALLOCATED(SITE)) DEALLOCATE(SITE)
         IF (ALLOCATED(FROZEN)) DEALLOCATE(FROZEN)
         IF (ALLOCATED(FROZENRES)) DEALLOCATE(FROZENRES)
         IF (ALLOCATED(INTFROZEN)) DEALLOCATE(INTFROZEN)
         IF (ALLOCATED(ANCHORCOORDS)) DEALLOCATE(ANCHORCOORDS)
         IF (ALLOCATED(NPERMSIZE)) DEALLOCATE(NPERMSIZE)
         IF (ALLOCATED(PERMGROUP)) DEALLOCATE(PERMGROUP)
         IF (ALLOCATED(ORDERNUM)) DEALLOCATE(ORDERNUM)
         IF (ALLOCATED(NPERMSIZEQCI)) DEALLOCATE(NPERMSIZEQCI)
         IF (ALLOCATED(PERMGROUPQCI)) DEALLOCATE(PERMGROUPQCI)
         IF (ALLOCATED(NPERMSIZEBACK)) DEALLOCATE(NPERMSIZEBACK)
         IF (ALLOCATED(PERMGROUPBACK)) DEALLOCATE(PERMGROUPBACK)
         IF (ALLOCATED(NSETS)) DEALLOCATE(NSETS)
         IF (ALLOCATED(SETS)) DEALLOCATE(SETS)
         IF (ALLOCATED(NSETSQCI)) DEALLOCATE(NSETSQCI)
         IF (ALLOCATED(NSETSBACK)) DEALLOCATE(NSETSBACK)
         IF (ALLOCATED(SETSQCI)) DEALLOCATE(SETSQCI)
         IF (ALLOCATED(SETSBACK)) DEALLOCATE(SETSBACK)
         IF (ALLOCATED(NGLJSPECIES)) DEALLOCATE(NGLJSPECIES)
         IF (ALLOCATED(GLJEPS)) DEALLOCATE(GLJEPS)
         IF (ALLOCATED(GLJSIG)) DEALLOCATE(GLJSIG)
         IF (ALLOCATED(CHARGE)) DEALLOCATE(CHARGE)
         IF (ALLOCATED(REPELTS)) DEALLOCATE(REPELTS)
         IF (ALLOCATED(LJREP_BLN)) DEALLOCATE(LJREP_BLN)
         IF (ALLOCATED(LJATT_BLN)) DEALLOCATE(LJATT_BLN)
         IF (ALLOCATED(A_BLN)) DEALLOCATE(A_BLN)
         IF (ALLOCATED(B_BLN)) DEALLOCATE(B_BLN)
         IF (ALLOCATED(C_BLN)) DEALLOCATE(C_BLN)
         IF (ALLOCATED(D_BLN)) DEALLOCATE(D_BLN)
         IF (ALLOCATED(BEADLETTER)) DEALLOCATE(BEADLETTER)
         IF (ALLOCATED(BLNSSTRUCT)) DEALLOCATE(BLNSSTRUCT)
         IF (ALLOCATED(WHICHORDER)) DEALLOCATE(WHICHORDER)
         IF (ALLOCATED(EPSALPHA)) DEALLOCATE(EPSALPHA)
         IF (ALLOCATED(DISTREF)) DEALLOCATE(DISTREF)
         IF (ALLOCATED(CPDISTREF)) DEALLOCATE(CPDISTREF)
         IF (ALLOCATED(MIN1REDO)) DEALLOCATE(MIN1REDO)
         IF (ALLOCATED(MIN2REDO)) DEALLOCATE(MIN2REDO)
         IF (ALLOCATED(CONDISTREF)) DEALLOCATE(CONDISTREF)
         IF (ALLOCATED(CONDISTREFLOCAL)) DEALLOCATE(CONDISTREFLOCAL)
         IF (ALLOCATED(CONDISTREFON)) DEALLOCATE(CONDISTREFON)
         IF (ALLOCATED(CONDISTREFLOCALON)) DEALLOCATE(CONDISTREFLOCALON)
         IF (ALLOCATED(CONCUT)) DEALLOCATE(CONCUT)
         IF (ALLOCATED(CONCUTLOCAL)) DEALLOCATE(CONCUTLOCAL)
         IF (ALLOCATED(CONDISTREFFIX)) DEALLOCATE(CONDISTREFFIX)
         IF (ALLOCATED(CONCUTFIX)) DEALLOCATE(CONCUTFIX)
         IF (ALLOCATED(CPCONDISTREF)) DEALLOCATE(CPCONDISTREF)
         IF (ALLOCATED(INTNEBIMAGES)) DEALLOCATE(INTNEBIMAGES)
         IF (ALLOCATED(CONGEOM)) DEALLOCATE(CONGEOM)
         IF (ALLOCATED(LJADDEPS)) DEALLOCATE(LJADDEPS)
         IF (ALLOCATED(LJADDREP)) DEALLOCATE(LJADDREP)
         IF (ALLOCATED(LJADDATT)) DEALLOCATE(LJADDATT)
         IF (ALLOCATED(COUL_SIGMA0)) DEALLOCATE(COUL_SIGMA0)
         IF (ALLOCATED(COUL_KQQ)) DEALLOCATE(COUL_KQQ)
         IF (ALLOCATED(CONACTIVE)) DEALLOCATE(CONACTIVE)
         IF (ALLOCATED(RESTRAINTARRAY)) DEALLOCATE(RESTRAINTARRAY)
         IF (ALLOCATED(ATOMACTIVE)) DEALLOCATE(ATOMACTIVE)
         IF (ALLOCATED(NITSTART)) DEALLOCATE(NITSTART)
         IF (ALLOCATED(RPMASSES)) DEALLOCATE(RPMASSES)
         IF (ALLOCATED(XMINA)) DEALLOCATE(XMINA)
         IF (ALLOCATED(XMINB)) DEALLOCATE(XMINB)
         IF (ALLOCATED(RBOPS)) DEALLOCATE(RBOPS)
         IF (ALLOCATED(SAVES)) DEALLOCATE(SAVES)
         IF (ALLOCATED(SAVEF)) DEALLOCATE(SAVEF)
         IF (ALLOCATED(ORDERI)) DEALLOCATE(ORDERI)
         IF (ALLOCATED(ORDERJ)) DEALLOCATE(ORDERJ)
         IF (ALLOCATED(REPPOW)) DEALLOCATE(REPPOW)
         IF (ALLOCATED(CONI)) DEALLOCATE(CONI)
         IF (ALLOCATED(CONJ)) DEALLOCATE(CONJ)
         IF (ALLOCATED(CONION)) DEALLOCATE(CONION)
         IF (ALLOCATED(CONJON)) DEALLOCATE(CONJON)
         IF (ALLOCATED(CONOFFLIST)) DEALLOCATE(CONOFFLIST)
         IF (ALLOCATED(CONOFFTRIED)) DEALLOCATE(CONOFFTRIED)
         IF (ALLOCATED(CONIFIX)) DEALLOCATE(CONIFIX)
         IF (ALLOCATED(CONJFIX)) DEALLOCATE(CONJFIX)
         IF (ALLOCATED(REPIFIX)) DEALLOCATE(REPIFIX)
         IF (ALLOCATED(REPJFIX)) DEALLOCATE(REPJFIX)
         IF (ALLOCATED(REPI)) DEALLOCATE(REPI)
         IF (ALLOCATED(REPJ)) DEALLOCATE(REPJ)
         IF (ALLOCATED(CPCONI)) DEALLOCATE(CPCONI)
         IF (ALLOCATED(CPCONJ)) DEALLOCATE(CPCONJ)
         IF (ALLOCATED(CPREPI)) DEALLOCATE(CPREPI)
         IF (ALLOCATED(CPREPJ)) DEALLOCATE(CPREPJ)
         IF (ALLOCATED(REPCUT)) DEALLOCATE(REPCUT)
         IF (ALLOCATED(NREPCUT)) DEALLOCATE(NREPCUT)
         IF (ALLOCATED(CPREPCUT)) DEALLOCATE(CPREPCUT)
         IF (ALLOCATED(REPCUTFIX)) DEALLOCATE(REPCUTFIX)
         IF (ALLOCATED(NREPI)) DEALLOCATE(NREPI)
         IF (ALLOCATED(NREPJ)) DEALLOCATE(NREPJ)
         IF (ALLOCATED(BESTPERM)) DEALLOCATE(BESTPERM)
         IF (ALLOCATED(RBGROUP)) DEALLOCATE(RBGROUP)
         IF (ALLOCATED(RBNINGROUP)) DEALLOCATE(RBNINGROUP)
         IF (ALLOCATED(TO_ALIGN)) DEALLOCATE(TO_ALIGN)
         IF (ALLOCATED(DIHETOTWIST)) DEALLOCATE(DIHETOTWIST)
         IF (ALLOCATED(XYPHI)) DEALLOCATE(XYPHI)
         IF (ALLOCATED(RERHOARRAY)) DEALLOCATE(RERHOARRAY)
         IF (ALLOCATED(IMRHOARRAY)) DEALLOCATE(IMRHOARRAY)
         IF (ALLOCATED(SOFT_SPHERE_RADII)) DEALLOCATE(SOFT_SPHERE_RADII)
         IF (ALLOCATED(OBSCHEMSHIFT)) DEALLOCATE(OBSCHEMSHIFT)
         IF (ALLOCATED(ENERGYCAM)) DEALLOCATE(ENERGYCAM)
         IF (ALLOCATED(SHIFTDIF)) DEALLOCATE(SHIFTDIF)
         IF (ALLOCATED(FORCEX)) DEALLOCATE(FORCEX)
         IF (ALLOCATED(FORCEY)) DEALLOCATE(FORCEY)
         IF (ALLOCATED(FORCEZ)) DEALLOCATE(FORCEZ)
         IF (ALLOCATED(MIEF_EPS)) DEALLOCATE(MIEF_EPS)
         IF (ALLOCATED(MIEF_SIG)) DEALLOCATE(MIEF_SIG)
         IF (ALLOCATED(MIEF_SITES)) DEALLOCATE(MIEF_SITES)
         IF (ALLOCATED(MIEF_U_RCUT)) DEALLOCATE(MIEF_U_RCUT)
         IF (ALLOCATED(MIEF_DUDR_RCUT)) DEALLOCATE(MIEF_DUDR_RCUT)
         IF (ALLOCATED(QCIXYZ)) DEALLOCATE(QCIXYZ)
         IF (ALLOCATED(BONDS)) DEALLOCATE(BONDS)
         IF (ALLOCATED(ATOMSTORES)) DEALLOCATE(ATOMSTORES)
         IF (ALLOCATED(DLDATA)) DEALLOCATE(DLDATA)
         IF (ALLOCATED(DLXS)) DEALLOCATE(DLXS)
         IF (ALLOCATED(DLYS)) DEALLOCATE(DLYS)
         IF (ALLOCATED(LAYERS_WIDTH)) DEALLOCATE(LAYERS_WIDTH)
         IF (ALLOCATED(N_HIDDEN)) DEALLOCATE(N_HIDDEN)
         IF (ALLOCATED(MLPDAT)) DEALLOCATE(MLPDAT)
         IF (ALLOCATED(MLPOUTCOME)) DEALLOCATE(MLPOUTCOME)
         IF (ALLOCATED(MLSUPOUTCOME)) DEALLOCATE(MLSUPOUTCOME)
         IF (ALLOCATED(MLMINWEIGHTS)) DEALLOCATE(MLMINWEIGHTS)
         IF (ALLOCATED(MLQDAT)) DEALLOCATE(MLQDAT)
         IF (ALLOCATED(MLQOUTCOME)) DEALLOCATE(MLQOUTCOME)
         IF (ALLOCATED(LJADDNN)) DEALLOCATE(LJADDNN)
         IF (ALLOCATED(COMMONCON)) DEALLOCATE(COMMONCON)
         IF (ALLOCATED(NCONCOMMON)) DEALLOCATE(NCONCOMMON)
         IF (ALLOCATED(MINPROBS)) DEALLOCATE(MINPROBS)
         IF (ALLOCATED(MLPBESTMIN)) DEALLOCATE(MLPBESTMIN)
         IF (ALLOCATED(R2INTS)) DEALLOCATE(R2INTS)
         IF (ALLOCATED(DIPINTS)) DEALLOCATE(DIPINTS)
         IF (ALLOCATED(KSAVE)) DEALLOCATE(KSAVE)
         IF (ALLOCATED(QCCOEFFA)) DEALLOCATE(QCCOEFFA)
         IF (ALLOCATED(QCCOEFFB)) DEALLOCATE(QCCOEFFB)
         IF (ALLOCATED(QCCOEFFASAVE)) DEALLOCATE(QCCOEFFASAVE)
         IF (ALLOCATED(QCCOEFFBSAVE)) DEALLOCATE(QCCOEFFBSAVE)
         IF (ALLOCATED(QCCOEFFAFIN)) DEALLOCATE(QCCOEFFAFIN)
         IF (ALLOCATED(QCCOEFFBFIN)) DEALLOCATE(QCCOEFFBFIN)
         IF (ALLOCATED(QCCOEFFATS)) DEALLOCATE(QCCOEFFATS)
         IF (ALLOCATED(QCCOEFFBTS)) DEALLOCATE(QCCOEFFBTS)
         IF (ALLOCATED(QCCOEFFAPLUS)) DEALLOCATE(QCCOEFFAPLUS)
         IF (ALLOCATED(QCCOEFFBPLUS)) DEALLOCATE(QCCOEFFBPLUS)
         IF (ALLOCATED(QCCOEFFAMINUS)) DEALLOCATE(QCCOEFFAMINUS)
         IF (ALLOCATED(QCCOEFFBMINUS)) DEALLOCATE(QCCOEFFBMINUS)
         IF (ALLOCATED(QCCOEFFG)) DEALLOCATE(QCCOEFFG)
         IF (ALLOCATED(QCCOEFFGSAVE)) DEALLOCATE(QCCOEFFGSAVE)
         IF (ALLOCATED(QCCOEFFGFIN)) DEALLOCATE(QCCOEFFGFIN)
         IF (ALLOCATED(QCCOEFFGTS)) DEALLOCATE(QCCOEFFGTS)
         IF (ALLOCATED(QCCOEFFGPLUS)) DEALLOCATE(QCCOEFFGPLUS)
         IF (ALLOCATED(QCCOEFFGMINUS)) DEALLOCATE(QCCOEFFGMINUS)
         IF (ALLOCATED(UCCAMP)) DEALLOCATE(UCCAMP)
         IF (ALLOCATED(UCCHAM)) DEALLOCATE(UCCHAM)
         IF (ALLOCATED(UCCOPS)) DEALLOCATE(UCCOPS)
         IF (ALLOCATED(UCCOPORDER)) DEALLOCATE(UCCOPORDER)
         IF (ALLOCATED(CONDISTATOM1)) DEALLOCATE(CONDISTATOM1)
         IF (ALLOCATED(CONDISTATOM2)) DEALLOCATE(CONDISTATOM2)
         IF (ALLOCATED(CONDIST)) DEALLOCATE(CONDIST)
         IF (ALLOCATED(KDIST)) DEALLOCATE(KDIST)
         IF (ALLOCATED(NODESTATE)) DEALLOCATE(NODESTATE)
         IF (ALLOCATED(NEIGHBS)) DEALLOCATE(NEIGHBS)
         IF (ALLOCATED(PAIRSTATE)) DEALLOCATE(PAIRSTATE)
         IF (ALLOCATED(GSQCASE)) DEALLOCATE(GSQCASE)
         IF (ALLOCATED(NODEWEIGHT)) DEALLOCATE(NODEWEIGHT)
         IF (ALLOCATED(SURFWEIGHT)) DEALLOCATE(SURFWEIGHT)
         IF (ALLOCATED(WETENERGY)) DEALLOCATE(WETENERGY)
         IF (ALLOCATED(WETTYPE)) DEALLOCATE(WETTYPE)
         IF (ALLOCATED(PMULTA1)) DEALLOCATE(PMULTA1)
         IF (ALLOCATED(PMULTA2)) DEALLOCATE(PMULTA2)
         IF (ALLOCATED(PMULTFRC)) DEALLOCATE(PMULTFRC)
         IF (ALLOCATED(BONDSOPEP)) DEALLOCATE(BONDSOPEP)
         IF (ALLOCATED(QCIALIGNATOMS)) DEALLOCATE(QCIALIGNATOMS)
         IF (ALLOCATED(QCILINEARATOMS)) DEALLOCATE(QCILINEARATOMS)

      END SUBROUTINE KEY_DEALLOCATE

END MODULE KEY
