PROGRAM TS_SEARCH
    USE COMMONS, ONLY: NOPT
    USE KEY, ONLY : BITSSALPHA, BITSSBETA
    USE KEY, ONLY : BITSSSTOP, BITSSMAXITER, BITSSSTEP, BITSS_coefiter
    USE KEY, ONLY : BITSSLBFGS_m, BITSSLBFGS_maxiter, BITSSLBFGS_maxstep, BITSSLBFGS_conv
    USE BITSSMODULE
    IMPLICIT NONE
    DOUBLE PRECISION :: COORDS1(2), COORDS2(2)
    NOPT = 2
    BITSSALPHA = 10
    BITSSBETA = 0.1
    BITSSSTOP = 0.01
    BITSSSTEP = 0.5
    BITSSMAXITER = 10
    BITSS_coefiter = 10000
    BITSSLBFGS_m = 5
    BITSSLBFGS_maxiter = 10000
    BITSSLBFGS_maxstep = 0.1
    BITSSLBFGS_conv = 1d-6

    COORDS1 = [-1.4, 0.]
    COORDS2 = [1.4, 0.]
    call bitss(COORDS1, COORDS2)
    print*, COORDS1
    print*, COORDS2
END PROGRAM TS_SEARCH
