PROGRAM TS_SEARCH
    USE COMMONS, ONLY: NOPT
    USE KEY, ONLY : BITSSALPHA, BITSSBETA
    USE KEY, ONLY : BITSSSTOP, BITSSMAXITER
    USE BITSSMODULE
    IMPLICIT NONE
    DOUBLE PRECISION, ALLOCATABLE, DIMENSION(:) :: COORDS !   MXATMS
    DOUBLE PRECISION :: COORDS1(2), COORDS2(2)
    NOPT = 0
    BITSSALPHA = 0.50D0
    BITSSBETA = 0.1D0
    BITSSSTOP = 0.0D0
    BITSSMAXITER = 0
    ALLOCATE(COORDS(NOPT))

    COORDS1 = [-1.4, 0.]
    COORDS2 = [1.4, 0.]
    call bitss(COORDS1, COORDS2)
    print*, COORDS1
    print*, COORDS2
END PROGRAM TS_SEARCH
