PROGRAM TS_SEARCH
    USE COMMONS, ONLY: NOPT
    USE KEY, ONLY : BITSSALPHA, BITSSBETA
    USE KEY, ONLY : BITSSSTOP, BITSSMAXITER
    IMPLICIT NONE
    DOUBLE PRECISION, ALLOCATABLE, DIMENSION(:) :: COORDS !   MXATMS
    NOPT = 0
    BITSSALPHA = 0.50D0
    BITSSBETA = 0.1D0
    BITSSSTOP = 0.0D0
    BITSSMAXITER = 0
    ALLOCATE(COORDS(NOPT))
END PROGRAM TS_SEARCH